apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: thedobra
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: "128m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - app.thedobra.dev
        - api.thedobra.dev
      secretName: thedobra-tls
  rules:
    - host: app.thedobra.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: thedobra-web
                port:
                  number: 3010
    - host: api.thedobra.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: thedobra-api
                port:
                  number: 8080
